{% set version = "0.6.1" %}

package:
  name: obvious-ci
  version: {{ version }}

source:
  url: https://github.com/pelson/Obvious-CI/archive/v{{ version }}.tar.gz
  fn: obvious-ci_v{{ version }}.tar.gz
  sha256: 03a39402a6c09cd4342109bebfe6aac05a09d11e04e39f7b2f0ddfcbd33d2d91
  patches:
    - miniconda_url.patch

build:
  number: 3
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - obvci_conda_build_dir = obvci.cli.conda_build_dir:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - anaconda-client
    - conda
    - conda-build

test:
  imports:
    - obvci
    - obvci.conda_tools
    - obvci.cli

  commands:
    - unset CONDA_NPY && obvci_conda_build_dir --help  # [not win]
    - obvci_conda_build_dir --help                     # [win]

about:
  home: https://github.com/pelson/Obvious-CI
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools to simplify Continuous Integration, particularly for conda building.

extra:
  recipe-maintainers:
    - pelson
    - mwcraig
