# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Crxiy30wUoaQBpfkwysC5VAHzzqtO6JDmmmXlZ3GgnvQTYWpLGfsL8AyV8DULnyPK+UMImm9RXNY3C+ZafyJ87LaZBnF0H0zqs9mpLvE0bSxoiChtBmXSNXvrCBMYnXNfr9p5yEu5IKWxoaEPp2XXwbBj3pLsuyIkY6pbfjZdJmCsoWCQ9OmOo6p9/ZMIJqC15VLBxiLsxExvzwkO3oGPK3TNnmHpRBr+ebEWZFURWhrr0FpspD0PZeXWJzqr0ohwgj3uTSurkaCDw0z6auYlo/2I97D2rCEsjcphFhyIltu1pDbtqfVELpW3YOGTkJmhA7gTapvgwTp1YLrEcLNRfPuf0shrqgdSjM6GsLOX1yILWFQDl0mAp0bO6/spXAz3kBVLQeYSBB8HHEAby0jcHNVHLQulpNUlHOy/iJsWZ+1s//6vMDm5B5Xw1neWc6/EEko/0eKqKxSXmQW28WvRSmkdbq1hb1nqAmUcaT8GOsFueo/gx4o9P6SshvBDy+EmjkK+JeukHIlO0AUK6ygs4zNWhgDgrfkeSVd/O3tkhcKIqkidF22PFxhZpTNCYo+0srpbGNyhtMiccbXfrmUv1E+aZlCfOtv9SEVvu8NNl8CAiwzDv8GZsbatrH2J2xmJZZLGhZqRId73iRV0hYs0xy06qerPrh0FA0uztMIhWo="

before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
