travis:
  secure:
    BINSTAR_TOKEN: Crxiy30wUoaQBpfkwysC5VAHzzqtO6JDmmmXlZ3GgnvQTYWpLGfsL8AyV8DULnyPK+UMImm9RXNY3C+ZafyJ87LaZBnF0H0zqs9mpLvE0bSxoiChtBmXSNXvrCBMYnXNfr9p5yEu5IKWxoaEPp2XXwbBj3pLsuyIkY6pbfjZdJmCsoWCQ9OmOo6p9/ZMIJqC15VLBxiLsxExvzwkO3oGPK3TNnmHpRBr+ebEWZFURWhrr0FpspD0PZeXWJzqr0ohwgj3uTSurkaCDw0z6auYlo/2I97D2rCEsjcphFhyIltu1pDbtqfVELpW3YOGTkJmhA7gTapvgwTp1YLrEcLNRfPuf0shrqgdSjM6GsLOX1yILWFQDl0mAp0bO6/spXAz3kBVLQeYSBB8HHEAby0jcHNVHLQulpNUlHOy/iJsWZ+1s//6vMDm5B5Xw1neWc6/EEko/0eKqKxSXmQW28WvRSmkdbq1hb1nqAmUcaT8GOsFueo/gx4o9P6SshvBDy+EmjkK+JeukHIlO0AUK6ygs4zNWhgDgrfkeSVd/O3tkhcKIqkidF22PFxhZpTNCYo+0srpbGNyhtMiccbXfrmUv1E+aZlCfOtv9SEVvu8NNl8CAiwzDv8GZsbatrH2J2xmJZZLGhZqRId73iRV0hYs0xy06qerPrh0FA0uztMIhWo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
