travis:
  secure:
    BINSTAR_TOKEN: exR4IDiPwXgdWwDZO/L5Vcl8Nn3QmdkbBBxJdHwnuz4dvdd85B+KxWkY22fTXa9mR75XeV5+8fhM2moUO6fLneRb3mC6ssT/Jr2prair9Piv7JG9u7DwIi/yLxOLPKe+p1xDIB1f8gYDDNW8yx6aLbG9i5I5lrdGaOvbWpi/8L8VTvw8rQcL4dYoQ+VVOODt73tRfNwxxtrLYzxhEaA7ZdOdeHodVqbQhbr9khEHlRwnlGLdRcoXRirnjirrVcHpv1kuisnoJ8/bNuq0TC1APjDWM9AICqc5eAN4r7h+rlH1kGFSgzLVrEKP2QzLKjKTjpnJtqE9Y4y9B4kEnE2pNit+gE8u/EHScWxX9/KAbuzExb8bfcbAa62EgsLT8Uuo2FmE5eEOQ//1xJUlclWB9Z7+BurULco3Q+6e1wEvHdTmiUb/cIc5hq4rkC8BW/bzaiqNEaOZSY4ES1OOf/Z4lunRXVbHoR05bGvWBjzwmuC2Oypg0SQ553cUk1P8hV9sScL7wTwS2VT88AUHDOLDP8GtUD6xgT02iML3vP40QLNiVKaTu9bHhR5794EDlmFQ6Zn21n8j+8r0WLKtiZrTOjDwahXn3BqtbHJDbQAV3POplQAeCqgFIzVZCzztMp2aEuwigiiHBiPP5Ci5ZZJxDz6bx8MVZWe/bXn1bBKezZI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
